spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.xabier.desafio: DEBUG

app:
  security:
    jwt:
      secret-key: Mi-ClaveSecretaJWT-XabierWolf
      seconds-expiration: 3600 # in seconds
 